version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2023!"
    ports:
      - "5432:5432"
    volumes:
      - /home/fastfood/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fast-food@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2023!"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge