apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_URL: jdbc:postgresql://dbfastfood:5432/fast-food
  POSTGRES_DB: fast-food
  POSTGRES_USER: postgres
