apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-fast-food
spec:
  selector:
    matchLabels:
      app: api-fast-food
  template:
    metadata:
      labels:
        app: api-fast-food
    spec:
      containers:
      - name: api-fast-food
        image: rafaelcarmonagil/fast-food:2.0
        env:
        - name: spring.profiles.active
          value: kubernetes
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: banco-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_URL
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: apifastfoodsvc
spec:
  selector:
    app: api-fast-food
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30010
  type: NodePort          
