name: pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Package
        run: ./gradlew clean build -x test
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Package
        run: ./gradlew test

  pre_build:
    steps:
      - run: "echo Logging in to Amazon ECR..."


  build_image:
    steps:
      - run: "echo Build started on `date`"


  post_build:
    steps:
      - run: "echo Build completed on `date`"
